### ISSUE TITLE
USER STORY: Hide the poll

### ISSUE THREAD

**Issue by richardreiter** [richardreiter/My-First-Agile-Project#5]
In order to automatically hide the poll **as an administrator,** I can **pick the expiry date** while **publishing the poll**

## Acceptance Criteria
  - Acceptance Criteria 1: The poll should disappear at 11:59 PM on the target date
  - Acceptance Criteria 2: The real estate of the "Poll" should be reserved on the home page. A message that says "Stay tuned, a new poll is coming soon" should appear if no other Poll is active.
  - Acceptance Criteria 3: The administrator expiry date should be at least 3 days after the current date.

## Tasks
  - [ ] Update the admin module view: the poll design (HTML and CSS) to include date picker
  - [ ] Update the website view: show "Stay tuned, a new poll is coming soon"
  - [ ] Create Javascript function to validate the expiry date is at least after 3 days.
  - [ ] Create a job to check expired Polls everyday at 11:59 PM and hide them
  - [ ] Update the controller function
  - [ ] Update unit test scripts
  - [ ] Test the functionality
